#!/bin/bash

if [ -z "$@" ];
then
	echo "Current setting is $(grep -E "#define BRGHT BRGHT_(.*)" kbdbacklight.c | rev | cut -d' ' -f1 | cut -d'_' -f1 | rev)"
	echo -e "Argument (case-insensitive) should be given as follows:\n \t Off - Disable backlighting \n\t Med - Enable medium brightness \n\t Max - Enable maximum brightness"
	exit 1
else
	sed -i "s/#define BRGHT BRGHT_.*/#define BRGHT BRGHT_`echo "$1" | awk '{print toupper($0)}'`/" kbdbacklight.c
	make
	read -r -p "Would you like to restart the systemd service? [Y/n] " response
	case "$response" in
		""|[yY][eE][sS]|[yY])
			systemctl restart kbdbacklight.service
			;;
		*)
			echo "Please restart systemd service manually"
			;;
	esac
fi
